"""add_user_fields

Revision ID: 665782603f4a
Revises: b18838a61e1f
Create Date: 2026-07-12 10:51:52.948941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '665782603f4a'
down_revision: Union[str, None] = 'b18838a61e1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mobile_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('users', sa.Column('email_status', sa.String(length=20), nullable=False, server_default='PENDING'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_status')
    op.drop_column('users', 'must_change_password')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'mobile_number')
    # ### end Alembic commands ###
